- README.md
> fix: edited the README

- client/components/Home.js
- client/components/Upload.js
- client/components/index.js
- client/components/main.js
- server/db/models/content.js
- server/db/models/event.js
- server/db/models/index.js
- server/db/models/user.js
- server/index.js
> Creating models: added content, event and user models, also created Mosaic, Upload and Home components

- client/components/Upload.js
- client/store/firebase.js
- client/store/index.js
- package-lock.json
- package.json
- secrets.js
> uploadFiles - trying to get firebase file upload working correctly

- .firebaserc
- client/App.js
- client/components/Upload.js
- client/store/firebase.js
- firebase.json
- public/index.html
- secrets.js
- storage.rules
> Firebase Storage is configured

- client/App.js
- client/components/Mosaic.js
- client/components/Upload.js
- client/store/content.js
- client/store/firebase.js
- client/store/index.js
- package-lock.json
- package.json
- script/seed.js
- server/api/content.js
- server/db/models/content.js
- Created content store (thunks, actions, action creators, etc...)
- Connected the Mosaic to the store
- Edited the POST api/content route  => POST api/content/images
- Created seed file with fillMurray()
- Added a few npm modules
> feat: Mosaic is connected to the store and to firebase

- README.md
> first development branch test pull request

- client/components/ContactList.js
- client/components/Dashboard.js
- client/components/EventList.js
- client/components/index.js
- server/api/contacts.js
- server/api/index.js
- server/db/models/contacts.js
- server/db/models/index.js
> features(contactList): added contact list models started on thunks

- client/components/Upload.js
- server/socket/index.js
> Exif img stuff

- client/components/Upload.js
- client/store/content.js
- client/store/index.js
- package-lock.json
- package.json
- server/api/content.js
> features(imageExif) - finished imageExif data using callbacks)

- client/components/Upload.js
- client/socket.js
- client/store/content.js
- client/store/index.js
- server/socket/index.js
> Socket config

- client/components/Upload.js
- client/store/content.js
- server/db/models/index.js
> feature: actually fixed the merge conflicts now

- client/components/SignUpForm.js
- public/style.css
> Fixed SignUp

- client/components/Mosaic.js
- client/components/Upload.js
- client/store/content.js
- server/api/content.js
- server/db/models/content.js
> feature: fixed mosaic and upload toggles

- client/components/LogInForm.js
- client/components/NavModal.js
- client/components/SignUpForm.js
- public/style.css
• Signup and login forms basic design
> signup and login forms: basic design

- client/components/SingleEvent.js
- client/store/twilio.js
- server/api/twilio.js
> Twilio message

- client/components/AddCommentForm.js
- client/components/CommentList.js
- client/components/Mosaic.js
- client/components/SingleContent.js
- client/components/Upload.js
- client/store/comments.js
- client/store/contacts.js
- client/store/index.js
- public/style.css
- server/api/comments.js
- server/api/contacts.js
- server/api/index.js
- server/api/twilio.js
- server/db/models/comments.js
- server/db/models/index.js
> feature: fixed mobile upload bug and added comments feature

- client/components/Upload.js
> Upload redux

- client/components/SingleContent.js
- client/components/Upload.js
- package-lock.json
- package.json
- public/helperFunctions.js
- server/api/content.js
- server/db/models/content.js
Map stuff working correctly, but we need to resize the container and the marker
> feat: map functioning correctly

- server/api/twilio.js
> twilio fix

- client/components/EventList.js
- client/components/Mosaic.js
- client/components/NavLoggedIn.js
- client/components/SingleEvent.js
- client/components/main.js
- client/store/content.js
- client/store/participants.js
- client/store/singleEvent.js
- server/api/contacts.js
- server/api/content.js
- server/api/events.js
- server/api/participants.js
- server/api/twilio.js
- server/db/models/comments.js
- server/db/models/contacts.js
- server/db/models/event.js
- server/db/models/user.js
> Clean up - cleaned up backend code in prep for code review, also switched uri's to use secrets instead of id's

- client/components/SingleContent.js
- client/components/SingleEvent.js
- client/store/twilio.js
- server/api/twilio.js
- server/db/models/contacts.js
> Twiliio - added participant secret to twilio texts

- client/components/Upload.js
- client/store/content.js
- server/api/content.js
- server/db/models/content.js
- server/socket/index.js
feat: Fixed Upload and Removed Map functionality
> Fixed Upload, Removed Map

- client/store/content.js
- server/api/content.js
> feat: Fixed Upload

- client/components/AddContactsToEventForm.js
- client/components/ContactForm.js
- client/components/CreateEventForm.js
- client/components/Dashboard.js
- client/components/SingleEvent.js
> feat: On submit close modals

- client/components/Mosaic.js
- client/components/Upload.js
- public/style.css
- utils/imgUtils.js
- webpack.config.js
> fixed the photo grid, it works like it should now

- client/components/ContactForm.js
- client/components/SingleEvent.js
> Twilio sucks nads

- client/components/Upload.js
> remove for error on upload

- client/components/CommentList.js
- client/components/SingleEvent.js
- client/components/Upload.js
- server/api/twilio.js
> Twilio stuff

- client/components/AddContactsToEventForm.js
- client/components/ContactList.js
- client/components/Dashboard.js
- client/components/EventList.js
- client/components/SingleEvent.js
- public/style.css
- server/db/models/user.js
> design: add participants modal

- client/components/Mosaic.js
- package.json
> Responsive grid

- client/components/AddContactsToEventForm.js
- client/components/SingleEvent.js
- client/components/Upload.js
- server/api/twilio.js
> feature - fixed selective twilio messaging

- client/components/AddContactsToEventForm.js
- client/components/SingleEvent.js
- client/components/Upload.js
- server/api/twilio.js
Reverts Gathr-io/Scrapbooker#94
> Revert "feature - fixed selective twilio messaging"

- server/auth/google.js
> feat: get first and last name from Google Auth

- client/components/AddContactsToEventForm.js
> feature: fixed add contact bugs

- client/components/SingleEvent.js
- client/components/Upload.js
- server/api/twilio.js
> feture: fixed twilio stuff merge conflict

- client/components/Upload.js
> instant upload fix

- client/components/Dashboard.js
- client/components/Mosaic.js
- client/components/SingleEvent.js
- client/store/twilio.js
> fixing twilio

- client/components/SingleEvent.js
> feature: adding organizer to email route

- client/components/CommentList.js
- client/components/Mosaic.js
- client/components/Upload.js
- client/socket.js
- client/store/comments.js
- client/store/content.js
- client/store/index.js
- server/api/comments.js
- server/api/twilio.js
- server/socket/index.js
> Comment socket

- package-lock.json
- package.json
- public/index.html
- server/index.js
> added favicon middleware
